name: Mirror Backup

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror repository
        run: |
          # Deshabilitar las credenciales por defecto de GitHub Actions
               git config --global credential.helper ""
               
               git config --global user.email "tu-email@ejemplo.com"
               git config --global user.name "TuNombre"
          
          # Agregar el remote usando tu PAT
               git remote add backup https://x-access-token:${{ secrets.BACKUP_TOKEN }}@github.com/${{ secrets.BACKUP_REPO }}.git
          
          # Forzar el push
               git push --mirror backup