name: Mirror Backup

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror repository
        run: |
          git config --global user.email "tu-email@ejemplo.com"
          git config --global user.name "TuNombre"
          # Usamos 'x-access-token' como usuario y el PAT como password
          git remote add backup https://x-access-token:${{ secrets.BACKUP_TOKEN }}@github.com/${{ secrets.BACKUP_REPO }}.git
          git push --mirror backup