name: Mirror Backup

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror repository
        run: |
          # 1. Borrar la configuración de credenciales inyectada por el checkout
               git config --global --unset-all http.https://github.com/.extraheader
          
          # 2. Configurar el acceso usando tu token
               git remote add backup https://x-access-token:${{ secrets.BACKUP_TOKEN }}@github.com/${{ secrets.BACKUP_REPO }}.git
          
          # 3. Empujar
               git push --mirror backup